const products = [
    {
        id: 1,
        name: "High-Speed Blender Pro",
        price: 299.99,
        originalPrice: 349.99,
        discount: "40% OFF",
        rating: 4.7,
        reviews: 256,
        itemsLeft: 10,
        boughtThisWeek: 16,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "kitchen",
        origin: "usa",
        color: "white",
        promotion: "sale",
        description: "Professional-grade blender for all your kitchen needs. High-speed motor and durable blades."
    },
    {
        id: 2,
        name: "Smart Coffee Maker",
        price: 199.99,
        originalPrice: 249.99,
        discount: "20% OFF",
        rating: 4.5,
        reviews: 128,
        itemsLeft: 5,
        boughtThisWeek: 8,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "kitchen",
        origin: "uk",
        color: "black",
        promotion: "best",
        description: "Wake up to the perfect cup of coffee with our smart coffee maker. Programmable and easy to use."
    },
    {
        id: 3,
        name: "Air Purifier X1",
        price: 149.99,
        originalPrice: 179.99,
        discount: "15% OFF",
        rating: 4.8,
        reviews: 312,
        itemsLeft: 15,
        boughtThisWeek: 24,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "cleaning",
        origin: "chine",
        color: "white",
        promotion: "new",
        description: "Keep your home air clean and fresh with the Air Purifier X1. Advanced filtration system."
    },
    {
        id: 4,
        name: "Robot Vacuum Cleaner",
        price: 399.99,
        originalPrice: 499.99,
        discount: "20% OFF",
        rating: 4.6,
        reviews: 450,
        itemsLeft: 8,
        boughtThisWeek: 12,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "cleaning",
        origin: "usa",
        color: "black",
        promotion: "best",
        description: "Effortless cleaning with our robot vacuum. Smart mapping and powerful suction."
    },
    {
        id: 5,
        name: "Smart Thermostat",
        price: 129.99,
        originalPrice: 159.99,
        discount: "18% OFF",
        rating: 4.9,
        reviews: 89,
        itemsLeft: 20,
        boughtThisWeek: 30,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "smart",
        origin: "canada",
        color: "white",
        promotion: "new",
        description: "Save energy and keep your home comfortable with our smart thermostat."
    },
    {
        id: 6,
        name: "Electric Kettle Elite",
        price: 49.99,
        originalPrice: 69.99,
        discount: "28% OFF",
        rating: 4.4,
        reviews: 567,
        itemsLeft: 40,
        boughtThisWeek: 50,
        image: "img/item.png",
        images: ["img/item.png", "img/item.png", "img/item.png", "img/item.png"],
        category: "kitchen",
        origin: "turkey",
        color: "orange",
        promotion: "sale",
        description: "Fast boiling and sleek design. The perfect addition to any kitchen."
    }
];

export default products;
